# Generated by Django 2.1.3 on 2018-11-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='stripe_customer_id',
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Expert', 'exp'), ('Basic', 'bas'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
